### ISSUE TITLE
Dynarec calcculation error somehwere.

### ISSUE THREAD

**Issue by carnage702** [emukidid/Wii64#3]
ever since wii64 1.0 and even on not64 there is a dynarec error  on atleast 3 games probably  more.

Castlevania,cstlevania legacy of darkness and Paperboy 64 will only start in intrepreter and play perfectly altough slow, if you start them in dynarec they wont start at all or start and dsi exception crash, the other day i got this dsi exception on castlevania  on not 64 if it helps anything

https://s1.postimg.org/25dccysd9r/IMG0446_A.jpg

**Comment by carnage702** [comment]
Confirmed they boot and work fine on mupen64plus with rice 2.5.0

**Comment by emukidid** [comment]
Castlevania 1 & 2 should be fixed now, Paperboy just black screens on dynarec now.

**Comment by carnage702** [comment]
thanks i played castlevania on 1.4.2 and with wiiu overclock it plays fine but paperboy still fails to work, guess its a diferent issue.

**Comment by carnage702** [comment]
Paperboy now works too.
